### ISSUE TITLE
Consider Orchestrate.io

### ISSUE THREAD

**Issue by joelabair** [greenca6/pokerplus#1]
Just a thought.  Feel free to close this issue at any point.

Orchestrate is a DBAAS powered by the AWS sphere.  https://orchestrate.io/

Benefits: 
* object store
* graph support
* free for limited use
* simple api
* highly performant
* DBA automation handled for us

Drawbacks:
* AWS network traffic and issues effect availability and latency.
* At some point-of-growth, > 50K ops, it will cost monthly.
  But depending on the app's architecture this may be a long way off.

PS.  Would you add me as a contributor to this project?

**Comment by greenca6** [comment]
Added you as a contributor.

So I guess with Orchestrate, the core benefit of it is to completely remove responsibilities from setting up/upkeep of your database? You basically just start querying.

**Comment by joelabair** [comment]
Correct. Data Base As A Service.  Simplifying deployment requirements.

**Comment by greenca6** [comment]
I like the idea of using this. Considering the small scale nature of this project, it's better to be sticking to strictly coding and design, and not have to worry about the stuff that's just more time consuming than actually helping us build the tool.

One thing I couldn't find on their site is anything about setting up test databases to use for unit testing. I assume this is all achievable through their GUI?
